/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Fernando
 */
public class FrmTragaPerras extends javax.swing.JFrame {

    /**
     * Creates new form FrmTragaPerras
     */
    Boolean iniciar;

    public FrmTragaPerras() {
        initComponents();
        iniciar = false;
    }

    public Boolean getIniciar() {
        return iniciar;
    }

    public void setIniciar(Boolean iniciar) {
        this.iniciar = iniciar;
    }

    public void actulizarCampo(modelo.Icon icon, char id) {
        switch (id) {
            case ('i') -> {
                cambiarImagen(icon, campoI);
            }
            case ('c') -> {
                cambiarImagen(icon, campoC);
            }
            case ('d') -> {
                cambiarImagen(icon, campoD);
            }
        }
    }

    public void cambiarImagen(modelo.Icon icon, javax.swing.JLabel cosa) {
        switch (icon) {
            case (icon.BAR) -> {
                ajustarImagen("/imagenes/bar.png", cosa);
            }
            case (icon.CAMPANAS) -> {
                ajustarImagen("/imagenes/bell.png", cosa);

            }
            case (icon.CEREZAS) -> {
                ajustarImagen("/imagenes/cherrys.png", cosa);
            }
            case (icon.ESTRELLA) -> {
                ajustarImagen("/imagenes/stars.png", cosa);
            }
            case (icon.LIMONES) -> {
                ajustarImagen("/imagenes/lemons.png", cosa);
            }
            case (icon.NARANJAS) -> {
                ajustarImagen("/imagenes/oranges.png", cosa);
            }
            case (icon.SANDIAS) -> {
                ajustarImagen("/imagenes/watermelon.png", cosa);
            }
            case (icon.SIETE) -> {
                ajustarImagen("/imagenes/seven.png", cosa);
            }
            case (icon.UVAS) -> {
                ajustarImagen("/imagenes/grapes.png", cosa);
            }
        }
    }

    private void ajustarImagen(String ubicacion, javax.swing.JLabel casilla) {
        ImageIcon image = new ImageIcon(getClass().getResource(ubicacion));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(casilla.getWidth(), casilla.getHeight(), Image.SCALE_DEFAULT));
        casilla.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campoD = new javax.swing.JLabel();
        campoC = new javax.swing.JLabel();
        campoI = new javax.swing.JLabel();
        palanca = new javax.swing.JLabel();
        traga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(campoI, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoD, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoI, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 280, 160));

        palanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palancaMouseClicked(evt);
            }
        });
        jPanel1.add(palanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 110, 50, 40));

        traga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tragaperras.png"))); // NOI18N
        jPanel1.add(traga, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 501, 543));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palancaMouseClicked
        iniciar = true;
        
          new Thread(() -> {
        Clip clip = null;

        try {
            InputStream audioStream = getClass().getResourceAsStream("/imagenes/Sonido.wav");
            if (audioStream == null) {
                throw new FileNotFoundException("No se pudo encontrar el archivo de sonido.");
            }
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(audioStream);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
            Thread.sleep(10000);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException | InterruptedException e) {
            System.out.println("Error al reproducir el archivo de sonido: " + e.getMessage());
        } finally {
            if (clip != null && clip.isRunning()) {
                clip.stop();
                clip.close();
            }
        }
    }).start();
    }//GEN-LAST:event_palancaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTragaPerras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTragaPerras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTragaPerras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTragaPerras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTragaPerras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoC;
    private javax.swing.JLabel campoD;
    private javax.swing.JLabel campoI;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel palanca;
    private javax.swing.JLabel traga;
    // End of variables declaration//GEN-END:variables
}
